name: Build and Release Cross-Platform

permissions:
  contents: write # Required to create a release and upload assets

on:
  push:
    branches:
      - main # Adjust to your desired branch

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check_commit.outputs.should_release }}
      version: ${{ steps.extract_info.outputs.version }}
      description: ${{ steps.extract_info.outputs.description }}
      prerelease: ${{ steps.extract_info.outputs.prerelease }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check commit message
        id: check_commit
        shell: bash
        run: |
          # Get the latest commit message
          commit_msg=$(git log -1 --pretty=%B)
          echo "Commit message:"
          echo "$commit_msg"
          
          # Check if it contains "Release v"
          if [[ "$commit_msg" == *"Release v"* ]]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Extract release info from commit message
        id: extract_info
        if: steps.check_commit.outputs.should_release == 'true'
        shell: bash
        run: |
          # Get the latest commit message
          commit_msg=$(git log -1 --pretty=%B)
          
          # Extract the version (matches digits and optional dash/letters)
          version=$(echo "$commit_msg" | sed -n 's/.*Release v\([[:alnum:].\-]\+\).*/\1/p')
          
          # Extract the description between the tilde markers.
          # This assumes the description is enclosed between lines containing only '~'
          description=$(echo "$commit_msg" | sed -n '/^~$/,/^~$/p' | sed '1d;$d')

          # Ensure a valid version was found
          if [ -z "$version" ]; then
            echo "No valid release version found in the commit message. Exiting."
            exit 1
          fi
          
          # Determine if it's a pre-release (if version contains a dash)
          if echo "$version" | grep -q '-'; then
            prerelease=true
          else
            prerelease=false
          fi

          echo "Version: $version"
          echo "Description: $description"
          echo "Prerelease: $prerelease"

          # Set outputs using the environment file method.
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "description<<EOF" >> $GITHUB_OUTPUT
          echo "$description" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "prerelease=$prerelease" >> $GITHUB_OUTPUT

  build-windows:
    needs: check-release
    if: needs.check-release.outputs.should_release == 'true'
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --windowed --name "Snipping Lens" --icon="my_icon.ico" --add-data="my_icon.png;." snipping_lens.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: ./dist/Snipping Lens.exe

  build-linux:
    needs: check-release
    if: needs.check-release.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-gi python3-dev libcairo2-dev pkg-config python3-dev xclip

      - name: Install Python dependencies
        run: pip install -r requirements.txt pygobject

      - name: Install AppImage tools
        run: |
          sudo apt-get install -y fuse libfuse2
          wget -q -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build AppImage
        run: |
          # Create AppDir structure
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          
          # Build executable
          pyinstaller --onefile --name snipping_lens snipping_lens.py
          
          # Copy executable and assets
          cp dist/snipping_lens AppDir/usr/bin/
          cp my_icon.png AppDir/usr/share/icons/hicolor/256x256/apps/snipping_lens.png
          
          # Create desktop file
          cat > AppDir/usr/share/applications/snipping_lens.desktop << EOF
          [Desktop Entry]
          Type=Application
          Name=Snipping Lens
          Exec=snipping_lens
          Icon=snipping_lens
          Categories=Utility;
          Terminal=false
          EOF
          
          # Create AppRun
          cat > AppDir/AppRun << EOF
          #!/bin/bash
          SELF=\$(readlink -f "\$0")
          HERE=\${SELF%/*}
          export PATH="\${HERE}/usr/bin:\${PATH}"
          export LD_LIBRARY_PATH="\${HERE}/usr/lib:\${LD_LIBRARY_PATH}"
          export XDG_DATA_DIRS="\${HERE}/usr/share:\${XDG_DATA_DIRS}"
          exec "\${HERE}/usr/bin/snipping_lens" "\$@"
          EOF
          
          chmod +x AppDir/AppRun
          
          # Generate AppImage
          ./appimagetool AppDir
          
          # Rename the AppImage
          mv Snipping_Lens-x86_64.AppImage SnippingLens-${{ needs.check-release.outputs.version }}-x86_64.AppImage

      - name: Build DEB package
        run: |
          # Create package structure
          mkdir -p debian/DEBIAN
          mkdir -p debian/usr/bin
          mkdir -p debian/usr/share/applications
          mkdir -p debian/usr/share/icons/hicolor/256x256/apps
          mkdir -p debian/etc/xdg/autostart
          
          # Copy executable and assets
          cp dist/snipping_lens debian/usr/bin/
          cp my_icon.png debian/usr/share/icons/hicolor/256x256/apps/snipping_lens.png
          
          # Create desktop file
          cat > debian/usr/share/applications/snipping_lens.desktop << EOF
          [Desktop Entry]
          Type=Application
          Name=Snipping Lens
          Exec=/usr/bin/snipping_lens
          Icon=/usr/share/icons/hicolor/256x256/apps/snipping_lens.png
          Categories=Utility;
          Terminal=false
          EOF
          
          # Create autostart file
          cp debian/usr/share/applications/snipping_lens.desktop debian/etc/xdg/autostart/
          
          # Create control file
          cat > debian/DEBIAN/control << EOF
          Package: snipping-lens
          Version: ${{ needs.check-release.outputs.version }}
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: python3, python3-gi, xclip
          Maintainer: Your Name <your.email@example.com>
          Description: Snipping Lens
           A tool to automatically search screenshots with Google Lens.
          EOF
          
          # Create postinst script to set permissions
          cat > debian/DEBIAN/postinst << EOF
          #!/bin/sh
          chmod +x /usr/bin/snipping_lens
          exit 0
          EOF
          
          chmod 755 debian/DEBIAN/postinst
          
          # Build the package
          dpkg-deb --build debian
          
          # Rename the package
          mv debian.deb snipping-lens_${{ needs.check-release.outputs.version }}_amd64.deb

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-packages
          path: |
            SnippingLens-${{ needs.check-release.outputs.version }}-x86_64.AppImage
            snipping-lens_${{ needs.check-release.outputs.version }}_amd64.deb

  create-release:
    needs: [check-release, build-windows, build-linux]
    if: needs.check-release.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-exe
          path: ./windows

      - name: Download Linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-packages
          path: ./linux

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check-release.outputs.version }}
          release_name: "v${{ needs.check-release.outputs.version }}"
          body: ${{ needs.check-release.outputs.description }}
          draft: false
          prerelease: ${{ needs.check-release.outputs.prerelease }}

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./windows/Snipping Lens.exe"
          asset_name: SnippingLens-Windows.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux AppImage Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./linux/SnippingLens-${{ needs.check-release.outputs.version }}-x86_64.AppImage"
          asset_name: SnippingLens-${{ needs.check-release.outputs.version }}-x86_64.AppImage
          asset_content_type: application/x-executable

      - name: Upload Linux DEB Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./linux/snipping-lens_${{ needs.check-release.outputs.version }}_amd64.deb"
          asset_name: snipping-lens_${{ needs.check-release.outputs.version }}_amd64.deb
          asset_content_type: application/vnd.debian.binary-package